### ISSUE TITLE
getItemById() does not return additional Data but the bare minimum

### ISSUE THREAD

**Issue by Colorfulstan** [jwalton/lol-js#16]
call: lolClient.getItemById(region, itemId, {'itemData': 'image'})
with lru cache enabled

```
TypeError: Cannot read property 'join' of undefined
at Client.<anonymous> (...\node_modules\lol-js\lib\api\lolStaticData.js:101:121)
at Client.eval [as getItems] (eval at <anonymous> (...\node_modules\promise-breaker\index.js:97:22), <anonymous>:11:26)
at Client.<anonymous> (...\node_modules\lol-js\lib\api\lolStaticData.js:113:19)
at Client.eval [as getItemById] (eval at <anonymous> (...\node_modules\promise-breaker\index.js:97:22), <anonymous>:11:26)
```

https://github.com/jwalton/lol-js/blob/master/src/api/lolStaticData.coffee#L118-L119

**Comment by Colorfulstan** [comment]
might just have used it wrong

**Comment by Colorfulstan** [comment]
Ok, so now that I use following call, there is a response but it doesn't include the image data
lolClient.getItemById(region, itemId, {'tags': ['image']})

even with {'tags':['all']} there is not more then the default data requested

(changed issue title acchordingly)
